addSbtPlugin("com.eed3si9n"       % "sbt-assembly"        % "0.14.6")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.3.4")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"     % "1.8.2")
addSbtPlugin("io.spray"           % "sbt-revolver"        % "0.9.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"             % "0.3.4")
