#!/usr/bin/env bash

set -e

# Builds the CLI and daemon and runs a small integration test

DIR=/tmp/landlord-test

cleanup() {
    rm -rf "$DIR"
}

trap cleanup EXIT

# Normalize dirs
SCRIPT_NAME="${BASH_SOURCE[0]}"
if [ -h "$SCRIPT_NAME" ]; then
    SCRIPT_NAME="$(readlink "$SCRIPT_NAME")"
fi
ROOT_DIR="$(cd "$(dirname "$SCRIPT_NAME")" && cd .. && pwd)"
cd "$ROOT_DIR"

# Build projects
(cd landlord && cargo build --release)
(cd landlordd && sbt daemon/stage)

# TODO remove the line below once alpakka #882, landlord #27, landlord #28 merged
exit 0

# Start landlordd
rm -rf "$DIR"
mkdir -p "$DIR"
landlordd/daemon/target/universal/stage/bin/landlordd --bind-dir-path "$DIR" --prevent-shutdown-hooks &
LANDLORDD_PID="$!"

while ! [ -e "$DIR/landlordd.sock" ]; do
    sleep 1
done

# Run a program that uses stdin and properties
OUTPUT=$(echo Testing | ./landlord/target/release/landlord -Dgreeting='hello world' -socket "$DIR/landlordd.sock" -cp landlordd/test/target/scala-2.12/classes example.Hello)
EXPECTED='hello world
Testing'

# Shutdown landlordd
kill "$LANDLORDD_PID"
wait

# Test that we got what we expected
[ "$OUTPUT" = "$EXPECTED" ]
