#!/usr/bin/env bash

set -e

# Builds the CLI and daemon and runs a small integration test, testing connectivity
# over TCP and Unix Domain Sockets.

DIR=/tmp/landlord-test

cleanup() {
    rm -rf "$DIR"
}

trap cleanup EXIT

# Normalize dirs
SCRIPT_NAME="${BASH_SOURCE[0]}"
if [ -h "$SCRIPT_NAME" ]; then
    SCRIPT_NAME="$(readlink "$SCRIPT_NAME")"
fi
ROOT_DIR="$(cd "$(dirname "$SCRIPT_NAME")" && cd .. && pwd)"
cd "$ROOT_DIR"

# Build projects
(cd landlordd && sbt clean compile "project daemon" "set Test / Keys.test := {}" stage) &
(cd landlord && cargo clean && cargo build --release) &
wait

# Start landlordd
rm -rf "$DIR"
mkdir -p "$DIR"
landlordd/daemon/target/universal/stage/bin/landlordd --host "unix://$DIR/landlordd.sock" &
LANDLORDD_PID="$!"
while ! [ -e "$DIR/landlordd.sock" ]; do sleep 1; done

# Setup socat for forwarding connections on TCP port 2375 to the unix domain socket (temporary until landlordd has TCP support)
socat -d -d TCP4-LISTEN:2375,fork "UNIX-CONNECT:$DIR/landlordd.sock" &
SOCAT_PID="$!"
while ! nc -z 127.0.0.1 2375; do sleep 1; done

# Run a program that uses stdin and properties
OUTPUT=$(echo Testing | ./landlord/target/release/landlord -Dgreeting='hello world' -H "unix://$DIR/landlordd.sock" -cp landlordd/test/target/scala-2.12/classes example.Hello)
# Run the same program again, but this time over TCP
OUTPUT2=$(echo Testing | ./landlord/target/release/landlord -Dgreeting='hello world' -H "tcp://127.0.0.1:2375" -cp landlordd/test/target/scala-2.12/classes example.Hello)
EXPECTED='hello world
Testing
Good Bye!'

# Shutdown landlordd and socat
kill "$LANDLORDD_PID"
kill "$SOCAT_PID"
wait

# Test that we got what we expected
EXPECTED='hello world
Testing
Good Bye!'

[ "$OUTPUT" = "$EXPECTED" ] && [ "$OUTPUT2" = "$EXPECTED" ]
